const Q=[
['Alertness','You are feeling sleepy while driving. What should you do?',['Open a window and continue','Stop somewhere safe and rest','Turn up the music','Drive faster'],1,'Fresh air and music do not overcome fatigue. Stop safely and rest before continuing.'],
['Road signs','What does a triangular road sign usually mean?',['A warning','An order','Tourist information','A parking place'],0,'Triangles warn you about hazards or conditions ahead.'],
['Safety margins','Why should you leave a large gap behind a cyclist in wet weather?',['They travel too slowly','They are hidden by spray','They need room around hazards','It lets you overtake closer'],2,'Cyclists may need to move around drains, puddles and other surface hazards.'],
['Rules of the road','At a zebra crossing, you should give way when:',['A pedestrian is waiting to cross','Traffic behind is close','The road is clear','Lights turn amber'],0,'Be ready to stop for pedestrians waiting to cross at a zebra crossing.'],
['Motorway rules','Which lane should you normally use on a motorway?',['The left-hand lane','The middle lane','The right-hand lane','Whichever is empty'],0,'Keep left unless overtaking or directed otherwise.'],
['Vehicle handling','What is the main risk of harsh braking on a wet road?',['Using less fuel','Loss of control','Warming tyres','Better grip'],1,'Wet roads reduce grip, so braking distances increase.'],
['Vulnerable road users','Before turning left, what should you check carefully?',['Fuel gauge','For cyclists alongside','Rear-view mirror only','Vehicle speed'],1,'Check mirrors and blind spots for people continuing ahead on your left.'],
['Traffic signs','A red circular sign generally tells you:',['Something is prohibited','There is a hazard','There is a service','The route is recommended'],0,'Red circles indicate prohibitions or restrictions.'],
['Weather','What should you do when visibility is reduced by fog?',['Drive closer','Use lights and slow down','Use full beam','Stop in a live lane'],1,'Use appropriate lights, reduce speed and leave more space.']];
const $=x=>document.querySelector(x),$$=x=>document.querySelectorAll(x);let S=JSON.parse(localStorage.rr||'{"answered":0,"correct":0,"records":[]}'),list=[],i=0,score=0,mode='mock',hazard=0,defer;
function persist(){localStorage.rr=JSON.stringify(S);stats()}function go(id){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav button').forEach(x=>x.classList.toggle('selected',x.dataset.page===id));scrollTo(0,0)}
function stats(){$('#practiceStat').textContent=S.answered+' questions answered';$('#answeredStat').textContent=S.answered;$('#correctStat').textContent=S.answered?Math.round(S.correct/S.answered*100)+'%':'0%';$('#mockStat').textContent=S.records.length;$('#records').innerHTML=S.records.length?S.records.map(x=>`<div class="record"><div><b>${x.score}/50 theory</b><small>Hazard practice: ${x.hazard}/5</small></div><small>${x.date}</small></div>`).join(''):'<p class="intro">No mock tests yet. Your completed tests will appear here.</p>'}
function begin(type,cat){mode=type;list=type==='mock'?Array.from({length:50},(_,n)=>Q[n%Q.length]).sort(()=>Math.random()-.5):Q.filter(x=>x[0]===cat);i=score=0;go('quiz');question()}
function question(){let q=list[i];$('#quizCounter').textContent=`${i+1} of ${list.length}`;$('#scoreLive').textContent=score+' correct';$('#quizProgress').style.width=i/list.length*100+'%';$('#questionCard').innerHTML=`<span class="tag">${q[0].toUpperCase()}</span><h2>${q[1]}</h2><div class="answers">${q[2].map((a,n)=>`<button class="answer" data-n="${n}"><b>${'ABCD'[n]}.</b> ${a}</button>`).join('')}</div>`;$$('.answer').forEach(b=>b.onclick=()=>answer(+b.dataset.n))}
function answer(n){let q=list[i],good=n===q[3];$$('.answer').forEach(b=>{b.disabled=true;let k=+b.dataset.n;b.classList.toggle('correct',k===q[3]);b.classList.toggle('wrong',k===n&&!good)});S.answered++;if(good){S.correct++;score++}persist();$('#questionCard').insertAdjacentHTML('beforeend',`<div class="explanation"><b>${good?'Correct.':'Not quite.'}</b> ${q[4]}</div><button class="primary next">${i===list.length-1?'Continue':'Next question'} →</button>`);$('.next').onclick=()=>{if(++i<list.length)question();else mode==='mock'?go('hazard'):go('progress')}}
function complete(){S.records.unshift({score,hazard,date:new Date().toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})});persist();let pass=score>=43;$('#resultTitle').textContent=pass?'Theory pass standard reached':'Keep building confidence';$('#resultScore').textContent=score+'/50';$('#resultDetail').textContent=(pass?'Pass mark achieved (43 needed)':'Pass mark is 43 out of 50')+' · Hazard practice '+hazard+'/5';$('#resultMessage').textContent=pass?'Excellent theory result. Keep practising hazard perception and review missed topics.':'Review explanations, target a category, then return for another mock.';go('results')}
$('#categoryList').innerHTML=[...new Set(Q.map(x=>x[0]))].map((c,n)=>`<button class="category" data-c="${c}"><span>${['☼','△','↔','↖','◌','⚠'][n%6]}</span><div><b>${c}</b><small>${Q.filter(x=>x[0]===c).length} practice question</small></div><strong>›</strong></button>`).join('');$$('.category').forEach(x=>x.onclick=()=>begin('practice',x.dataset.c));$('#signGrid').innerHTML=[['◯','Red circle','Prohibition or restriction'],['△','Red triangle','Warning ahead'],['▭','Blue rectangle','Information or instruction'],['⬡','STOP','Stop: give way'],['◇','Give way','Give priority'],['◉','National speed limit','Limit varies']].map(x=>`<article class="sign"><div class="sign-symbol">${x[0]}</div><b>${x[1]}</b><small>${x[2]}</small></article>`).join('');$$('[data-page]').forEach(x=>x.onclick=()=>go(x.dataset.page));$('#startMock').onclick=()=>begin('mock');$('#exitQuiz').onclick=()=>go('home');$('#hazardTap').onclick=()=>{hazard=5;$('#hazardFeedback').textContent='Good anticipation — the pedestrian may move into the road.';$('#hazardTap').disabled=true};$('#finishHazard').onclick=complete;$('#clearRecords').onclick=()=>{if(confirm('Clear all results saved on this device?')){S={answered:0,correct:0,records:[]};persist()}};addEventListener('beforeinstallprompt',e=>{e.preventDefault();defer=e;$('#installBtn').hidden=false});$('#installBtn').onclick=()=>{defer?.prompt();$('#installBtn').hidden=true};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');stats();
