document.addEventListener('DOMContentLoaded',()=>{
  const $=s=>document.querySelector(s),read=()=>JSON.parse(localStorage.getItem('driveable-learning')||'{"saved":[],"signScore":0,"daily":0,"day":""}'),write=x=>localStorage.setItem('driveable-learning',JSON.stringify(x));
  const today=new Date().toDateString(),initial=read();if(initial.day!==today){initial.day=today;initial.daily=0;write(initial)}
  $('#home').insertAdjacentHTML('beforeend',`<section class="learning-hub"><p class="kicker">BUILD CONFIDENCE</p><h2>Learning tools</h2><p class="daily-goal">Today’s goal: <b>${read().daily}/10</b> practice questions</p><button data-page="signquiz">Road-sign quiz</button><button data-page="revision">My revision list</button><button data-page="testday">Test-day checklist</button></section>`);
  $('main').insertAdjacentHTML('beforeend','<section id="signquiz" class="page"><div class="top"><button class="back" data-page="home">←</button><div><p class="kicker">ROAD-SIGN QUIZ</p><h1>What does this sign mean?</h1></div></div><div id="signQuizCard" class="learning-card"></div></section><section id="revision" class="page"><div class="top"><button class="back" data-page="home">←</button><div><p class="kicker">REVISION</p><h1>Saved for later</h1></div></div><div id="revisionList" class="learning-card"></div></section><section id="testday" class="page"><div class="top"><button class="back" data-page="home">←</button><div><p class="kicker">TEST DAY</p><h1>Arrive prepared</h1></div></div><div class="learning-card checklist"><h2>Before you travel</h2><label><input type="checkbox"> Bring your photocard driving licence</label><label><input type="checkbox"> Check your booking time and route</label><label><input type="checkbox"> Arrive with time to settle in</label><h2>During the test</h2><label><input type="checkbox"> Flag questions and use Review before submitting</label><label><input type="checkbox"> Click when a hazard develops, not repeatedly</label><p><a href="https://www.gov.uk/book-theory-test" target="_blank" rel="noreferrer">Check current GOV.UK guidance ↗</a></p></div></section>');
  const show=id=>{window.page?.(id);if(id==='signquiz')quiz();if(id==='revision')revision()};
  function revision(){const d=read(),e=$('#revisionList');e.innerHTML=d.saved.length?d.saved.map((x,i)=>`<article><b>${x.topic}</b><h3>${x.question}</h3><p>${x.answer}</p><button data-remove="${i}">Remove</button></article>`).join(''):'<h2>Your list is clear</h2><p>Save difficult practice questions here for later.</p>';e.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{d.saved.splice(+b.dataset.remove,1);write(d);revision()})}
  function quiz(){const all=window.SIGN_CATALOGUE||[],q=all[Math.floor(Math.random()*all.length)],opts=[q,...all.filter(x=>x.category===q.category&&x.name!==q.name).sort(()=>Math.random()-.5).slice(0,3)].sort(()=>Math.random()-.5),e=$('#signQuizCard');e.innerHTML=`<p class="kicker">${q.category}</p><img src="${q.image}" alt="Road sign"><h2>What does this sign mean?</h2><div class="quiz-choices">${opts.map(x=>`<button>${x.name}</button>`).join('')}</div><p class="muted">Score: ${read().signScore}</p>`;e.querySelectorAll('.quiz-choices button').forEach(b=>b.onclick=()=>{const ok=b.textContent===q.name;b.parentElement.querySelectorAll('button').forEach(x=>x.disabled=true);b.className=ok?'correct':'wrong';if(ok){const d=read();d.signScore++;write(d)}e.insertAdjacentHTML('beforeend',`<p>${ok?'Correct — well spotted.':'Correct answer: '+q.name}</p>`)})}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-page="signquiz"],[data-page="revision"],[data-page="testday"]');if(b)show(b.dataset.page);const a=e.target.closest('.answers .answer');if(a)setTimeout(()=>{const q=$('#quizCard .question');if(!q||q.querySelector('.save-revision'))return;const h=q.querySelector('h2')?.textContent,c=q.querySelector('.correct')?.textContent,t=q.querySelector('.tag')?.textContent;if(!h||!c)return;const d=read(),today=new Date().toDateString();if(d.day!==today){d.day=today;d.daily=0}d.daily++;write(d);const goal=$('.daily-goal b');if(goal)goal.textContent=d.daily+'/10';const b=document.createElement('button');b.className='link save-revision';b.textContent='Save for revision';b.onclick=()=>{const d=read();if(!d.saved.some(x=>x.question===h))d.saved.unshift({topic:t,question:h,answer:c});write(d);b.textContent='Saved'};q.append(b)},0)},true);
  function insights(){const list=window.driveableMockAnalysis||[],misses=window.driveableMockMisses||[],result=$('#result');if(!result||$('#resultInsights'))return;const box=document.createElement('section');box.id='resultInsights';box.className='result-insights';box.innerHTML=`${list.length?`<h2>Focus next</h2><p>Practise the areas that cost you the most marks.</p>${list.slice(0,3).map(([topic,count])=>`<button data-focus="${topic}"><b>${topic}</b><span>${count} to revisit →</span></button>`).join('')}`:'<h2>Strong work</h2><p>You answered every question correctly.</p>'}${misses.length?`<details><summary>Review ${misses.length} missed question${misses.length===1?'':'s'}</summary>${misses.map(x=>`<article><b>${x.topic}</b><h3>${x.question}</h3><p><strong>Your answer:</strong> ${x.answer}</p><p><strong>Correct answer:</strong> ${x.correct}</p><p>${x.explain}</p></article>`).join('')}</details>`:''}`;result.querySelector('.score').after(box);box.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>window.start('practice',b.dataset.focus))}
  document.addEventListener('click',e=>{if(e.target.closest('#submitMock,#endTest'))setTimeout(insights,50)},true);
});
